In [1]:
import pandas as pd
import numpy as np

#### Reading Data

In [13]:
data = pd.read_csv('../Datasets/Flavors.csv')
data2 = pd.read_csv('../Datasets/Flavors.csv', sep=',', header = None, names=['1','2','3','4'])
data2.head(2)

,,1,2,3,4
Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Mint Chocolate Chip,Vanilla,Yes,10,8,18

In [14]:
text_file = pd.read_csv('../Datasets/countries of the world.csv')

In [16]:
json_file = pd.read_json('../Datasets/json_sample.json')
json_file.head(3)

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [17]:
excel_file = pd.read_excel('../Datasets/Athletes.xlsx', sheet_name='Details')
excel_file.head(2)

              Name     NOC           Discipline
0  AALERUD Katrine  Norway         Cycling Road
1      ABAD Nestor   Spain  Artistic Gymnastics

1. Head - return top rows from data
2. tail - return last rows from data

In [6]:
data.head(3)
data.tail(3)

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [14]:
data.head(-2)       # Ignore Last 2 Rows
data.tail(-2)       # Ignore first 2 Rows

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

### Information Functions
1. info - return detailed information about data like index column name non null count as dtype
2. Desc - return statistics information about the data

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Flavor          9 non-null      object
 1   Base Flavor     9 non-null      object
 2   Liked           9 non-null      object
 3   Flavor Rating   9 non-null      float64
 4   Texture Rating  9 non-null      float64
 5   Total Rating    9 non-null      float64
dtypes: float64(3), object(3)
memory usage: 564.0+ bytes

In [24]:
# Describe function provide descriptive statistics about the data
data.describe()

       Flavor Rating  Texture Rating  Total Rating
count         9.0000        9.000000      9.000000
mean          6.6000        6.177778     12.800000
std           2.5387        1.478832      4.030509
min           2.3000        3.400000      5.700000
25%           4.7000        5.000000      9.700000
50%           6.9000        6.500000     13.400000
75%           8.2000        7.100000     15.300000
max          10.0000        8.000000     18.000000

In [ ]:
# Shape give rows and columns count of data
data.shape

(9, 6)

In [ ]:
# Give total size of data
data.size

54

In [15]:
data.items

<bound method DataFrame.items of                    Flavor Base Flavor Liked  Flavor Rating  Texture Rating  \
0     Mint Chocolate Chip     Vanilla   Yes           10.0             8.0
1               Chocolate   Chocolate   Yes            8.8             7.6
2                 Vanilla     Vanilla    No            4.7             5.0
3            Cookie Dough     Vanilla   Yes            6.9             6.5
4              Rocky Road   Chocolate   Yes            8.2             7.0
5               Pistachio     Vanilla    No            2.3             3.4
6             Cake Batter     Vanilla   Yes            6.5             6.0
7              Neapolitan     Vanilla    No            3.8             5.0
8  Chocolte Fudge Brownie   Chocolate   Yes            8.2             7.1

   Total Rating
0          18.0
1          16.6
2           9.7
3          13.4
4          15.2
5           5.7
6          12.5
7           8.8
8          15.3  >

In [11]:
data.dtypes

Flavor             object
Base Flavor        object
Liked              object
Flavor Rating     float64
Texture Rating    float64
Total Rating      float64
dtype: object

#### Selecting Columns

In [16]:
data['Base Flavor']

0      Vanilla
1    Chocolate
2      Vanilla
3      Vanilla
4    Chocolate
5      Vanilla
6      Vanilla
7      Vanilla
8    Chocolate
Name: Base Flavor, dtype: object

In [17]:
# Selecting Multiple columns
data[['Base Flavor', 'Flavor']]

  Base Flavor                  Flavor
0     Vanilla     Mint Chocolate Chip
1   Chocolate               Chocolate
2     Vanilla                 Vanilla
3     Vanilla            Cookie Dough
4   Chocolate              Rocky Road
5     Vanilla               Pistachio
6     Vanilla             Cake Batter
7     Vanilla              Neapolitan
8   Chocolate  Chocolte Fudge Brownie